### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by hidden-tom** [ethz-spylab/realistic-adv-examples#1]
Hello,

I just did a fresh install (pip install via requirements) and got the following error running main.py:

```ModuleNotFoundError: No module named 'lovely_tensors'```

Maybe one for requirements.txt?

Cheers!

Tom

**Comment by dedeswim** [comment]
Hi,
Thanks a lot for pointing this out! Since I was using the library just to debug, I remove its usage in the repository. Let me know if everything works now!

**Comment by hidden-tom** [comment]
All good, thanks for the fast update!
